sudo: required
services:
    - docker

before_install:
    - docker build -t miladelpiero1/docker-react -f Dockerfile.dev .

scripts:
    - docker run miladelpiero1/docker-react npm run test -- --coverage