sudo: required
services:
    - docker

before_install:
    - docker build -t miladelpiero1/docker-react -f Dockerfile.dev .

scripts:
    - docker run miladelpiero1/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-test"
    env: "env-test"
    bucket_name: "elasticbeanstalk-us-east-1-411026478373"
    bucket_path: "docker-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY